name: build-docs

# Limits workflow concurrency to only the latest commit in the PR.
concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

on:
  push:
    branches: [main, next]
    paths:
      - "docs/**"
      - ".github/workflows/build-docs.yml"
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - "docs/**"
      - ".github/workflows/build-docs.yml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-docs:
    name: Build Documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: docs/package-lock.json

      - name: Install dependencies
        working-directory: ./docs
        run: npm ci

      - name: Build documentation
        working-directory: ./docs
        run: npm run build:dev
