name: Trigger Aggregator Docs Rebuild

on:
  push:
    branches: [next]

jobs:
  notify:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Send repository_dispatch to aggregator
        uses: peter-evans/repository-dispatch@a628c95fd17070f003ea24579a56e6bc89b25766
        with:
          # PAT that can access the central aggregator repository
          token: ${{ secrets.DOCS_REPO_TOKEN }}
          repository: ${{ vars.DOCS_AGGREGATOR_REPO }}
          event-type: rebuild
